dist: trusty
language: java
jdk:
  - oraclejdk8

before_install:
  - mvn license:check-file-header -Dlicense.licenseName=bsd_2 -Dlicense.failOnNotUptodateHeader=true -Dlicense.failOnMissingHeader=true

deploy:
  provider: script
  script: cd $TRAVIS_BUILD_DIR && bash build-resources/travis-release.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
